<a href="https://colab.research.google.com/github/Dug0/Dug0/blob/main/Dugo_NLP_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NLP Assignment

In [ ]:
import nltk
import spacy
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import matplotlib.pyplot as plt
from wordcloud import WordCloud
import numpy as np
import pandas as pd
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('maxent_ne_chunker')
nltk.download('words')
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk import ngrams
nlp = spacy.load("en_core_web_sm")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping chunkers/maxent_ne_chunker.zip.
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Unzipping corpora/words.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


## 1. Text Preprocessing

In [ ]:
import nltk
import sys
!{sys.executable} -m nltk.downloader all
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

def download_nltk_resources():
    """Ensure all required NLTK resources are available"""
    required_resources = {
        'tokenizers/punkt': 'punkt',
        'corpora/stopwords': 'stopwords',
        'taggers/averaged_perceptron_tagger': 'averaged_perceptron_tagger',
        'corpora/wordnet': 'wordnet'
    }

    for path, package in required_resources.items():
        try:
            nltk.data.find(path)
        except LookupError:
            print(f"Downloading NLTK resource: {package}")
            nltk.download(package)

# Download required resources
download_nltk_resources()

def preprocess_text(text):
    """
    Complete text preprocessing pipeline:
    1. Lowercasing
    2. Tokenization
    3. Punctuation removal
    4. Stopword removal
    """
    # Lowercase conversion
    text = text.lower()

    # Tokenization
    tokens = word_tokenize(text)

    # Punctuation removal using regex
    tokens = [re.sub(r'[^\w\s]', '', token) for token in tokens]

    # Remove empty strings and stopwords
    stop_words = set(stopwords.words('english'))
    cleaned_tokens = [token for token in tokens
                     if token and token not in stop_words]

    return cleaned_tokens

# Example usage
text = "Natural Language Processing is a fascinating field. It combines linguistics and computer science!"
processed_tokens = preprocess_text(text)
print("Processed tokens:", processed_tokens)



<frozen runpy>:128: RuntimeWarning: 'nltk.downloader' found in sys.modules after import of package 'nltk', but prior to execution of 'nltk.downloader'; this may result in unpredictable behaviour
[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_eng.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data.

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


## 2. Tokenization and N-grams


In [ ]:
bigrams = list(ngrams(cleaned_tokens, 2))
print("Bigrams:", bigrams)

NameError: name 'cleaned_tokens' is not defined

## 3. Named Entity Recognition (NER)


In [ ]:
import spacy

# Load the English NLP model (required for NER)
nlp = spacy.load("en_core_web_sm")

# Example sentence
sentence = "John Piper went to Addis Ababa in 2021."

# Process the sentence with spaCy
doc = nlp(sentence)

# Extract and print named entities
for ent in doc.ents:
    print(ent.text, ent.label_)

John Piper PERSON
Addis Ababa GPE
2021 DATE


## 4. Converting Text to Numbers


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

sentences = [
    "I love machine learning.",
    "Natural language processing is a part of AI.",
    "AI is the future."
]

# CountVectorizer
count_vec = CountVectorizer()
X_count = count_vec.fit_transform(sentences)
print("Count Vectorizer Output:\n", X_count.toarray())
print("Vocabulary:", count_vec.get_feature_names_out())

# TfidfVectorizer
tfidf_vec = TfidfVectorizer()
X_tfidf = tfidf_vec.fit_transform(sentences)
print("\nTF-IDF Vectorizer Output:\n", X_tfidf.toarray())
print("Vocabulary:", tfidf_vec.get_feature_names_out())

Count Vectorizer Output:
 [[0 0 0 0 1 1 1 0 0 0 0 0]
 [1 0 1 1 0 0 0 1 1 1 1 0]
 [1 1 1 0 0 0 0 0 0 0 0 1]]
Vocabulary: ['ai' 'future' 'is' 'language' 'learning' 'love' 'machine' 'natural' 'of'
 'part' 'processing' 'the']

TF-IDF Vectorizer Output:
 [[0.         0.         0.         0.         0.57735027 0.57735027
  0.57735027 0.         0.         0.         0.         0.        ]
 [0.30650422 0.         0.30650422 0.40301621 0.         0.
  0.         0.40301621 0.40301621 0.40301621 0.40301621 0.        ]
 [0.42804604 0.5628291  0.42804604 0.         0.         0.
  0.         0.         0.         0.         0.         0.5628291 ]]
Vocabulary: ['ai' 'future' 'is' 'language' 'learning' 'love' 'machine' 'natural' 'of'
 'part' 'processing' 'the']


## 5. Word Embeddings (Advanced)


In [ ]:
# Note: en_core_web_sm does not have word vectors. You can install and use en_core_web_md
# Uncomment below to install and load the medium model if needed.
# !python -m spacy download en_core_web_md
# nlp = spacy.load("en_core_web_md")

# Example word vector
word = nlp("statistics")[0]
print("Vector for 'statistics':\n", word.vector)

Vector for 'statistics':
 [-0.41690463  1.7669348  -0.32461268 -0.26368254  0.41903955 -0.82435656
  1.7759601   1.1799244  -0.5343528   0.6726327   0.7025496  -0.87155217
 -0.45009452 -0.08444379 -0.39110148  0.48391783 -0.49917215 -0.40737742
  0.73089695 -0.31702182 -1.150731   -0.11625078 -0.34413397  0.17965207
  0.52622896  0.27015153  0.31332934 -0.22146185 -0.08495548  0.9944842
  0.13876066  0.35442764 -0.43736774  0.03322983 -0.6362076  -0.5977872
 -0.02763485  0.7287043  -0.5479296   0.14031199 -0.24462259 -0.9931303
 -0.36293048 -0.527912    0.82666934  0.32168573  0.17400952 -0.67557496
 -0.5535587  -1.0791624   0.9105729  -0.99583316 -0.30374682 -0.4599661
 -0.26409948  1.2360638   1.3152149  -0.44581082 -0.17534947  0.7200817
 -0.6993394  -0.02322084 -0.18029906 -0.4500663   0.4424851   1.0675678
 -0.03988652  0.34501317 -0.21803448 -0.28003377 -0.14238608  0.22508669
 -0.09779706  1.0541928   0.0536457  -0.4404735   0.5476637  -0.11951113
 -1.1615727   0.33190468 -0.495